[package]
name = "init"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.134"
aws = { path = "../aws", optional = true }
system = { path = "../system"}

[[bin]]
name = "init"
path = "init.rs"
